[[pages]]
path="src/Home.py"
name="Home"
icon="ğŸ "

[[pages]]
path="src/app_pages/CustomerList.py"
name="Customer List"
icon="ğŸ“–"

[[pages]]
path="src/app_pages/BuildPromptTemplate.py"
name="Build Prompt Template"
icon="ğŸª„"

[[pages]]
path="src/app_pages/PromptCatalog.py"
name="Prompt Catalog"
icon="ğŸ“–"

[[pages]]
path="src/app_pages/EmailGenerationWizard.py"
name="Email Generation Wizard"
icon="ğŸ§™ğŸ»â€â™€ï¸"