[[pages]]
path="src/Home.py"
name="Home"
icon="ğŸ "

[[pages]]
path="src/app_pages/DataViewer.py"
name="Data Viewer"
icon="ğŸ“–"

[[pages]]
path="src/app_pages/PromptEngineer.py"
name="Prompt Engineering"
icon="ğŸª„"

[[pages]]
path="src/app_pages/PromptCatalog.py"
name="Prompt Catalog"
icon="ğŸ“–"

[[pages]]
path="src/app_pages/EmailGenerationWizard.py"
name="Email Generation Wizard"
icon="ğŸ§™ğŸ»â€â™€ï¸"